# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Server
source:           docs
destination:      _gh_pages
host:             0.0.0.0
port:             9001
url:              http://sandersforpresident.github.io/
baseurl:          /bootstrap
encoding:         UTF-8

# Custom vars
current_version:  0.0.2
repo:             https://github.com/SandersForPresident/bootstrap
sass_repo:        https://github.com/SandersForPresident/bootstrap

download:
  source:         https://github.com/SandersForPresident/bootstrap
  dist:           https://github.com/SandersForPresident/bootstrap
  sass:           https://github.com/SandersForPresident/bootstrap

blog:             http://blog.getbootstrap.com
expo:             http://expo.getbootstrap.com

# Old urls
# cdn:
#  css:            https://github.com/SandersForPresident/bootstrap/dist/css/bootstrap.min.css
#  css_theme:      https://github.com/SandersForPresident/bootstrap/dist/css/bootstrap-theme.min.css
#  js:             https://github.com/SandersForPresident/bootstrap/dist/js/bootstrap.min.js

# New urls
cdn:
  css:			  http://coders.forsanders.com/bootstrap/dist/css/bootstrap.min.css
  css_theme:      http://coders.forsanders.com/bootstrap/dist/css/bootstrap-theme.min.css
  js:             http://coders.forsanders.com/bootstrap/dist/css/bootstrap.min.js

